version: 4.0.70
steps:
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
  - prompt: Click on the "Business Loan" link.
    commands:
      - command: hover-text
        text: Business Loan
        description: link for Business Loan
        action: click
